### 1. Импорт библиотеки NumPy с общепринятым сокращением.

In [2]:
!pip install numpy jupyter
import numpy as np

### 2. Примеры создания массивов:

#### - Из обычных списков

In [24]:
arr = np.array([1, 2, 3, 4]) # Одномерный массив 
arr

array([1, 2, 3, 4])

#### - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [23]:
arr = np.zeros((3, 4)) # Двумерный массив из нулей размером 3 на 4
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr = np.ones(5) # Массив из единиц
arr

array([1., 1., 1., 1., 1.])

In [18]:
arr = np.arange(5) # Массив в диапазоне [0, 5)
arr

array([0, 1, 2, 3, 4])

In [8]:
arr = np.eye(7) # Единичная матрица размером 7 на 7
arr

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### 3. Демонстрация атрибутов:

#### - вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [25]:
arr = np.array([[1, 2], [4, 5], [7, 8]])
arr.shape # Форма массива (в нашем случае - 3 на 2)

(3, 2)

In [28]:
arr.dtype # Тип данных (в нашем случае - целочисленный)

dtype('int64')

### 4. Примеры индексирования и срезов:

#### - получение отдельного элемента;

In [7]:
arr = np.array([[ 0,  1,  2,  3],
               [4, 5, 6, 7],
               [8, 9, 10, 11],
               [12, 13, 14, 15],
               [16, 17, 18, 19]])
arr[3,2] # Обращение к элементу на 4-ой строке в 3-ем столбце

np.int64(14)

#### - извлечение подмассива с помощью среза.

In [18]:
arr = np.random.sample((5, 4)) # Рандомно заполненный массив
print(arr)
arr[1:4] # Получение 2-4 строки из массива

[[0.72655512 0.43232245 0.75761516 0.52734989]
 [0.22235899 0.51006387 0.03931478 0.44713914]
 [0.48271535 0.70656321 0.92947527 0.15341   ]
 [0.06492891 0.74701801 0.6079326  0.59862855]
 [0.81127541 0.48128381 0.09047152 0.4238908 ]]


array([[0.22235899, 0.51006387, 0.03931478, 0.44713914],
       [0.48271535, 0.70656321, 0.92947527, 0.15341   ],
       [0.06492891, 0.74701801, 0.6079326 , 0.59862855]])

### 5. Примеры векторных операций и базовых статистик:

#### - поэлементное сложение или умножение массивов;

In [20]:
arr1 = np.array([[ 0,  1,  2,  3],
               [4, 5, 6, 7]])
arr2 = np.array([[12, 13, 14, 15],
               [16, 17, 18, 19]]) 
arr1 * arr2 # Поэлементное умножение массивов

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133]])

#### - вычисление средней величины (`mean`) или другой простой статистики.

In [23]:
arr = np.array([1, 2, 3, 4, 5])
print('Средняя величина:', arr.mean())

Средняя величина: 3.0
